logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: localhost # rabbitMQ的ip地址
    port: 5672 # 端口
    username: hello
    password: hello
    virtual-host: hello
    listener:
      simple:
        prefetch: 1